language: ruby
rvm:
- 2.2.3
before_script:
- chmod +x ./script/cibuild
script: "./script/cibuild"
install: bundle install
env global:
- NOKOGIRI_USE_SYSTEM_LIBRARIES=true
env:
  global:
  - secure: UaQarG47oNnN0j0q3f9EL+OtXhP7EPp180guJ2wI60eJRXy2y2+Q/BBZjlVrDVa6H3EB1gd9n2yCYMdA9zzUvmg8pkVaJo7j7mdBtMOZzLLgleURBUXKEh4PNQsvxjgCx/99ZV6zLDfvyT463YoSBqUzRx7DiBWkaIyl/WaP45srQ2FbU7r4wTLnf9+2+jqARdQ++yRBL8xs4hwtOVYIjFWvIv7ETouDYQ6eXoilIqeBXwyqm5wFQNnXeGiIDT3mjDWmmXovKUPEBFqrbuQC4hK4JLx3hjVP4CNIwX7Ir37DzirP1MUtUykdKXE62Ur+a5V2dl35JYhKJpYBUK8a+gEr8oARsbSFIv/cSzvp2vpSzhl+SDmI7qGNA6WPDuiPIajbNAWB5elaTQiNXU/2DZKhMxk52QTjXBWsJBAul5uBBBd4sxN1jhITS406bFTtGyzPRP9LBai7165honYXoOc+i/m1iRT/B98andCQGwsY4FpQbdNcSxoaXRgyrvHRVL2aTK2UwrA3AWAiinviRm0bXtGSPtWWV/XIlUKnzrs1BXVtD1Gk6XKPXk62V8fsInHRvW7QM207ghFuw366q/pAj/PBS71uVJ7kwb7uw9DIUEp/pIGHKaNjKDwK9mzwB0ppoXj9/Ph3F8Wr24+tmNQeBR0IkPsowsYhcakRFtk=
  - secure: c9W8KX6RVlW3upG5AezAYDVv49dnIeGN1RC9dZ796dtKJ6qzJCSdG5eJ4o3h08ekwRiTOLvtD7CR//oyJn0s7J8vviUSApfXzn8M9567g9gATX6a4ds1z0toq5H7FtHymFafl/fpwn8Zq8uQwGjA4yCUKRWWVguIJz2sKGesLZV49Y8595Dvm72MaPYCFbiVvaVq7wg76xbl0o7e1hUKLX3H7cW4K66KndvMqODbdb54Qkf5s1AmkMGQ8BgGemj1+SVnyaov8XHXbST0iixJdHNHDguSvByC3C2MAib3pK6FQtD5K0ZgeeMI2YfkWBRzSkEns+20QnzZDAKhi3g8+PBSF4XUKxalWtvdHcwYdLgXdNaPg5NgJv6imgZgallcV6nhWgHsyol7toHwTPbkc3mDgQBkRoXgn+AQOrXy22mFXF/8T8pdygmQAqKnl/P1moyTfOYwlm4uHVyjasmhOQxW9KarU22ZtmUavPmkdo+3RyNTwDOlYjhwScX0/CBLT9REvD0W4bgfC3Wy6Xx0Buzx+vYXX3KosOC4ruvCWfjroj3R7yrk8yPcTBjGj/axIZaume8tIhvVJ2hgN+yAY0lJ6Jw9vuA26/XTnkns2UiKp/QYADYctFrUX6P7hefQ1UAXBRhNBKqAD5IKqwm3ZEwKNYnJXOXeXYcj1pV/58g=
