language: ruby
rvm:
- 2.2.3
before_script:
- chmod +x ./script/cibuild
script: "./script/cibuild"
install: bundle install
env global:
- NOKOGIRI_USE_SYSTEM_LIBRARIES=true
env:
  global:
  - secure: y9/elahBjSj9nZ2cBp1abjrD1T0TIBqoPM62X4RB/iw2jBumrf2w5Xg5V47iLCcyeQGfjbQnU1HAsfk/uKOfAmoEnAaPMrICOQju8lCFD3KQZZBIWc8yi9F+0GVSwDuLeT57p1xmq7PwV5BMcHABBtcNveJq8s4403ldHzw61+i0lJboh9lpBjrI7t1wDz4GdOgbYOviuR/i59WeSCUrqdE/Ua+NifRldCZYMhD6+DrW1FYAfa4sV0F+QrthCfWZkkI3SbNhQTKIVWID/7P4jFVBOA7JscjdHNxVamIPmGFJUM8VE0uGGXg7YVvzyK75mPrXEkfgi1HOkAbqlsW3zaOPp4vVMa8LH0tSTTri4NtGDN5lW5n0HVfOC9w307dbbGzF+6ilrADEV3fkq3FbWXzChfaso+vAHDh1ne33c4XB50PFKnWJ1yI4nBxBwXiynjUx3XrXj2z7HK57zwMn7IsNTr5oTS8ZqrJ36ah22YLeqayZDSo4pmYd7AE2JKfa4TTG/nSUPsZH95MGSbIAt0SKR3p06hjSRx3wA3XAIfVLqH0CkzLYpCTBsXLSlLJs0EY/oPa9ZqVN1OmxrWFl3187eQ+Tm+IIuZP5My0WwEMtKnQdketFJJeaxPyiRyVCpA/P4mnHEI59qK7w52Nm3gAMNDSFn/kMlSNDdD37+gc=
  - secure: u32CX7EhHrKAtWPlhACaYJGa40uBeuiZzqdbR/oYwzurOpZG0qSWPouGIuFAMPHl8BjAIGtYEmQ30A9gYGs1o1+/qNik9FrmodfRrL05ixW9ggaDJNGx8bYVXgwNjYnbiFVnNH2woOBiI1EdXuuHWumJeSS6j3VSXJnGBUOOkRSeWZiGln8sFVBqoN6no55NZRCVwb0DuEKwLwEKxwVBWOnnmeXYZjjhKmF5Rs2ZeC36ip04z9/lxpgh74f5ti2z7F8qEIaToEstAAb7Zp/C2nTgWbs3TVf4WON4twMk/13H7VDOf+dw2hPbOS1NU9H4SWLAYE3Ryl+XHScBjMo2XEXMV1odxzJoVw+dTyU6HnyEj5UlVn3bmhjzIWJeg+g01kRcVEOLHcTXx1XOsUveFWD0AQQonqL23tEEl8veTWIifVHB+g8T7uz1G4IENcLV59FMN5da33jHD2Z0oPGVPvuS8jcTufBAYNTR2xaJK5XvizJirCHYgs6JOXhwxli2hEbKppwT/jFh8zU7VFjTwHv6qDx67U4p5B8Y+3AuPv2H9m7J483aes5NZzL8p78LeIXJ18LY+vAuB8g6s4RwwLXMl/bHWgx+A/9CKLY8OL8Dss3CW00mY1jrBgKWJoF9yPpQ5clPHtkp1YUUy/XrxmMKhZJmc8sK++3P9jJqBSo=
