# Site settings
title: Refugee Survey
email: 
description: Climate change is quickly becoming a growing factor in the global refugee crisis.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://forcetheclimate.com" # the base hostname & protocol for your site

permalink: pretty

# Build settings
markdown: kramdown

exclude: [vendor,'Gemfile','Gemfile.lock','Readme.md']

#Assets Pipeline
assets:

  sources:
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/fonts
    - _assets

  # js_compressor: uglifier
  # css_compressor: sass